services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: namialus/namialusweb-web:latest
    ports:
      - "2000:80"
    volumes:
      - .:/app
      - /app/node_modules
